### ISSUE TITLE
cannot get the cert

### ISSUE THREAD

**Issue by laye0619** [aploium/zmirror-onekey#8]
Hi there, thanks for your wonderful plugin. I met the error when I tried to using one key program. The error was it cannot get the cert. I was sure that I have set the DNS (aliyun) correctly. And when I tried to get the cert manually by /etc/certbot/certbot-auto certonly XXXXXXX

I get 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /root/.local/share/letsencrypt/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 1

**Comment by laye0619** [comment]
BTW, I was using Ubuntu 16.04 x86_64 with VPS of bandwagon.

**Comment by aploium** [comment]
Sorry I can't figure out which caused your problem 😞  by your given information.

However, you may try obtain an cert manually.
Please see [this](https://github.com/aploium/zmirror-onekey#证书获取失败)
